version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    container_name: mysql-api-emergency-tool
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
  cache:
    image: redis:6.2-alpine
    container_name: redis-api-emergency-tool
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  minio:
    image: bitnami/minio:latest
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    networks:
      - minionetwork
    volumes:
      - "minio_data:/data"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=!9nX.yhc3XNtfLjUeeQn
      - MINIO_DEFAULT_BUCKETS=s3-salesorchestrator

networks:
  minionetwork:
    driver: bridge

volumes:
  db:
  node_modules:
  cache:
  minio_data:
    driver: local
